# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Searle lab"
title:              "Searle lab at the Ohio State University"
description:        "This is a page for Searle lab, we are a bioinformatics and mass spectrometry lab at the Ohio State University"


# URL
url:                http://searlelab.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
#  - name:           "home"
#    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publication"
  - name:           "research"
    href:           "/research"
  - name:           "resources"
    href:           "/resources"
  - name:           "software"
    href:           "/software"
#  - name:           "blog"
#    href:           "/blog"
  - name:           "work with us"
    href:           "/jobs"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  -
    scope:
      path:         ""
      type:         "software"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
  software:
    output: true
    permalink: /software/:title/index.html
